Compiled from "CWE396_Catch_Generic_Exception__Throwable_14.java"
public class testcases.CWE396_Catch_Generic_Exception.CWE396_Catch_Generic_Exception__Throwable_14 extends testcasesupport.AbstractTestCase {
  public testcases.CWE396_Catch_Generic_Exception.CWE396_Catch_Generic_Exception__Throwable_14();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method testcasesupport/AbstractTestCase."<init>":()V
       4: return

  public void bad() throws java.lang.Throwable;
    Code:
       0: getstatic     #7                  // Field testcasesupport/IO.staticFive:I
       3: iconst_5
       4: if_icmpne     24
       7: ldc           #13                 // String Test
       9: invokestatic  #15                 // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
      12: pop
      13: goto          24
      16: astore_1
      17: ldc           #23                 // String Caught Throwable
      19: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      22: aload_1
      23: athrow
      24: return
    Exception table:
       from    to  target type
           7    13    16   Class java/lang/Throwable

  private void good1() throws java.lang.Throwable;
    Code:
       0: getstatic     #7                  // Field testcasesupport/IO.staticFive:I
       3: iconst_5
       4: if_icmpeq     15
       7: ldc           #29                 // String Benign, fixed string
       9: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      12: goto          32
      15: ldc           #13                 // String Test
      17: invokestatic  #15                 // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
      20: pop
      21: goto          32
      24: astore_1
      25: ldc           #33                 // String Caught Exception
      27: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      30: aload_1
      31: athrow
      32: return
    Exception table:
       from    to  target type
          15    21    24   Class java/lang/NumberFormatException

  private void good2() throws java.lang.Throwable;
    Code:
       0: getstatic     #7                  // Field testcasesupport/IO.staticFive:I
       3: iconst_5
       4: if_icmpne     24
       7: ldc           #13                 // String Test
       9: invokestatic  #15                 // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
      12: pop
      13: goto          24
      16: astore_1
      17: ldc           #33                 // String Caught Exception
      19: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      22: aload_1
      23: athrow
      24: return
    Exception table:
       from    to  target type
           7    13    16   Class java/lang/NumberFormatException

  public void good() throws java.lang.Throwable;
    Code:
       0: aload_0
       1: invokevirtual #35                 // Method good1:()V
       4: aload_0
       5: invokevirtual #40                 // Method good2:()V
       8: return

  public static void main(java.lang.String[]) throws java.lang.ClassNotFoundException, java.lang.InstantiationException, java.lang.IllegalAccessException;
    Code:
       0: aload_0
       1: invokestatic  #43                 // Method mainFromParent:([Ljava/lang/String;)V
       4: return
}
