Compiled from "CWE396_Catch_Generic_Exception__Throwable_10.java"
public class testcases.CWE396_Catch_Generic_Exception.CWE396_Catch_Generic_Exception__Throwable_10 extends testcasesupport.AbstractTestCase {
  public testcases.CWE396_Catch_Generic_Exception.CWE396_Catch_Generic_Exception__Throwable_10();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method testcasesupport/AbstractTestCase."<init>":()V
       4: return

  public void bad() throws java.lang.Throwable;
    Code:
       0: getstatic     #7                  // Field testcasesupport/IO.staticTrue:Z
       3: ifeq          23
       6: ldc           #13                 // String Test
       8: invokestatic  #15                 // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
      11: pop
      12: goto          23
      15: astore_1
      16: ldc           #23                 // String Caught Throwable
      18: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      21: aload_1
      22: athrow
      23: return
    Exception table:
       from    to  target type
           6    12    15   Class java/lang/Throwable

  private void good1() throws java.lang.Throwable;
    Code:
       0: getstatic     #29                 // Field testcasesupport/IO.staticFalse:Z
       3: ifeq          14
       6: ldc           #32                 // String Benign, fixed string
       8: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      11: goto          31
      14: ldc           #13                 // String Test
      16: invokestatic  #15                 // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
      19: pop
      20: goto          31
      23: astore_1
      24: ldc           #36                 // String Caught Exception
      26: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      29: aload_1
      30: athrow
      31: return
    Exception table:
       from    to  target type
          14    20    23   Class java/lang/NumberFormatException

  private void good2() throws java.lang.Throwable;
    Code:
       0: getstatic     #7                  // Field testcasesupport/IO.staticTrue:Z
       3: ifeq          23
       6: ldc           #13                 // String Test
       8: invokestatic  #15                 // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
      11: pop
      12: goto          23
      15: astore_1
      16: ldc           #36                 // String Caught Exception
      18: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      21: aload_1
      22: athrow
      23: return
    Exception table:
       from    to  target type
           6    12    15   Class java/lang/NumberFormatException

  public void good() throws java.lang.Throwable;
    Code:
       0: aload_0
       1: invokevirtual #38                 // Method good1:()V
       4: aload_0
       5: invokevirtual #43                 // Method good2:()V
       8: return

  public static void main(java.lang.String[]) throws java.lang.ClassNotFoundException, java.lang.InstantiationException, java.lang.IllegalAccessException;
    Code:
       0: aload_0
       1: invokestatic  #46                 // Method mainFromParent:([Ljava/lang/String;)V
       4: return
}
