Compiled from "CWE396_Catch_Generic_Exception__Exception_08.java"
public class testcases.CWE396_Catch_Generic_Exception.CWE396_Catch_Generic_Exception__Exception_08 extends testcasesupport.AbstractTestCase {
  public testcases.CWE396_Catch_Generic_Exception.CWE396_Catch_Generic_Exception__Exception_08();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method testcasesupport/AbstractTestCase."<init>":()V
       4: return

  private boolean privateReturnsTrue();
    Code:
       0: iconst_1
       1: ireturn

  private boolean privateReturnsFalse();
    Code:
       0: iconst_0
       1: ireturn

  public void bad() throws java.lang.Throwable;
    Code:
       0: aload_0
       1: invokevirtual #7                  // Method privateReturnsTrue:()Z
       4: ifeq          24
       7: ldc           #13                 // String Test
       9: invokestatic  #15                 // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
      12: pop
      13: goto          24
      16: astore_1
      17: ldc           #23                 // String Caught Exception
      19: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      22: aload_1
      23: athrow
      24: return
    Exception table:
       from    to  target type
           7    13    16   Class java/lang/Exception

  private void good1() throws java.lang.Throwable;
    Code:
       0: aload_0
       1: invokevirtual #31                 // Method privateReturnsFalse:()Z
       4: ifeq          15
       7: ldc           #34                 // String Benign, fixed string
       9: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      12: goto          32
      15: ldc           #13                 // String Test
      17: invokestatic  #15                 // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
      20: pop
      21: goto          32
      24: astore_1
      25: ldc           #23                 // String Caught Exception
      27: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      30: aload_1
      31: athrow
      32: return
    Exception table:
       from    to  target type
          15    21    24   Class java/lang/NumberFormatException

  private void good2() throws java.lang.Throwable;
    Code:
       0: aload_0
       1: invokevirtual #7                  // Method privateReturnsTrue:()Z
       4: ifeq          24
       7: ldc           #13                 // String Test
       9: invokestatic  #15                 // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
      12: pop
      13: goto          24
      16: astore_1
      17: ldc           #23                 // String Caught Exception
      19: invokestatic  #25                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      22: aload_1
      23: athrow
      24: return
    Exception table:
       from    to  target type
           7    13    16   Class java/lang/NumberFormatException

  public void good() throws java.lang.Throwable;
    Code:
       0: aload_0
       1: invokevirtual #38                 // Method good1:()V
       4: aload_0
       5: invokevirtual #41                 // Method good2:()V
       8: return

  public static void main(java.lang.String[]) throws java.lang.ClassNotFoundException, java.lang.InstantiationException, java.lang.IllegalAccessException;
    Code:
       0: aload_0
       1: invokestatic  #44                 // Method mainFromParent:([Ljava/lang/String;)V
       4: return
}
