Compiled from "CWE586_Explicit_Call_to_Finalize__basic_13.java"
public class testcases.CWE586_Explicit_Call_to_Finalize.CWE586_Explicit_Call_to_Finalize__basic_13 extends testcasesupport.AbstractTestCase {
  public testcases.CWE586_Explicit_Call_to_Finalize.CWE586_Explicit_Call_to_Finalize__basic_13();
    Code:
       0: aload_0
       1: invokespecial #3                  // Method testcasesupport/AbstractTestCase."<init>":()V
       4: return

  public void bad() throws java.lang.Throwable;
    Code:
       0: new           #9                  // class testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper
       3: dup
       4: invokespecial #11                 // Method testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper."<init>":()V
       7: astore_1
       8: aload_1
       9: invokevirtual #12                 // Method testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper.sayHello:()V
      12: aload_1
      13: invokevirtual #15                 // Method testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper.finalize:()V
      16: goto          39
      19: astore_2
      20: ldc           #20                 // String An error occurred.
      22: invokestatic  #22                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      25: aload_1
      26: invokevirtual #15                 // Method testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper.finalize:()V
      29: goto          39
      32: astore_3
      33: aload_1
      34: invokevirtual #15                 // Method testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper.finalize:()V
      37: aload_3
      38: athrow
      39: return
    Exception table:
       from    to  target type
           8    12    19   Class java/lang/Exception
           8    12    32   any
          19    25    32   any

  private void good1() throws java.lang.Throwable;
    Code:
       0: new           #9                  // class testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper
       3: dup
       4: invokespecial #11                 // Method testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper."<init>":()V
       7: astore_1
       8: aload_1
       9: invokevirtual #12                 // Method testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper.sayHello:()V
      12: aconst_null
      13: astore_1
      14: goto          33
      17: astore_2
      18: ldc           #20                 // String An error occurred.
      20: invokestatic  #22                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      23: aconst_null
      24: astore_1
      25: goto          33
      28: astore_3
      29: aconst_null
      30: astore_1
      31: aload_3
      32: athrow
      33: return
    Exception table:
       from    to  target type
           8    12    17   Class java/lang/Exception
           8    12    28   any
          17    23    28   any

  private void good2() throws java.lang.Throwable;
    Code:
       0: new           #9                  // class testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper
       3: dup
       4: invokespecial #11                 // Method testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper."<init>":()V
       7: astore_1
       8: aload_1
       9: invokevirtual #12                 // Method testcases/CWE586_Explicit_Call_to_Finalize/CWE586_Explicit_Call_to_Finalize__basic_Helper.sayHello:()V
      12: aconst_null
      13: astore_1
      14: goto          33
      17: astore_2
      18: ldc           #20                 // String An error occurred.
      20: invokestatic  #22                 // Method testcasesupport/IO.writeLine:(Ljava/lang/String;)V
      23: aconst_null
      24: astore_1
      25: goto          33
      28: astore_3
      29: aconst_null
      30: astore_1
      31: aload_3
      32: athrow
      33: return
    Exception table:
       from    to  target type
           8    12    17   Class java/lang/Exception
           8    12    28   any
          17    23    28   any

  public void good() throws java.lang.Throwable;
    Code:
       0: aload_0
       1: invokevirtual #26                 // Method good1:()V
       4: aload_0
       5: invokevirtual #31                 // Method good2:()V
       8: return

  public static void main(java.lang.String[]) throws java.lang.ClassNotFoundException, java.lang.InstantiationException, java.lang.IllegalAccessException;
    Code:
       0: aload_0
       1: invokestatic  #34                 // Method mainFromParent:([Ljava/lang/String;)V
       4: return
}
